### ISSUE TITLE
/swim doesn't work properly when only installed on server

### ISSUE THREAD

**Issue by onycius** [YukkuriLaboratory/FabPose#11] opened 2024-07-09 08:06 UTC
fabpose 1.0.0+1.21

hello,

when fabpose is installed server-side only, every pose works properly visually for the user except for /swim, which causes the player to sink for a split second and then return back to the standing position. other players can see the user perform the /swim fine. having fabpose installed on both client and server seems to solve this issue, so i'm not sure if this is unavoidable/intended.

error server-side when doing /swim:
[01:01:16] [Server thread/ERROR]: Failed to pose
net.fill1890.fabsit.error.PoseException$StateException: null
        at net.yukulab.fabpose.extension.ServerPlayerEntityKt.canPose(ServerPlayerEntity.kt:83) ~[fabpose-1.0.0+1.21.jar:?]
        at net.yukulab.fabpose.extension.ServerPlayerEntityKt.pose(ServerPlayerEntity.kt:42) ~[fabpose-1.0.0+1.21.jar:?]
        at net.yukulab.fabpose.extension.ServerPlayerEntityKt.pose$default(ServerPlayerEntity.kt:18) ~[fabpose-1.0.0+1.21.jar:?]
        at net.yukulab.fabpose.command.Command.registerPoseCommands$lambda$5$lambda$4(Command.kt:49) ~[fabpose-1.0.0+1.21.jar:?]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.class_8865.method_54416(class_8865.java:29) ~[server-intermediary.jar:?]
        at net.minecraft.class_8865.execute(class_8865.java:13) ~[server-intermediary.jar:?]
        at net.minecraft.class_8856.method_54405(class_8856.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_8847.method_54388(class_8847.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_8854.method_54390(class_8854.java:107) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_54313(class_2170.java:379) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:309) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_58590(class_3244.java:1319) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_44356(class_3244.java:1307) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by turtton** [comment] 2024-07-13 00:37
Thanks for the report.

> the player to sink for a split second and then return back to the standing position

This is expected behavior. I have yet to find a way to continue the swim motion in the vanilla client.
I will specify this as a known issue later to avoid misunderstandings.

That said, the error output is an unexpected problem. Please let this issue remain Open for later investigation.

**Comment by turtton** [comment] 2024-07-24 06:48
> [01:01:16] [Server thread/ERROR]: Failed to pose
> net.fill1890.fabsit.error.PoseException$StateException: null

Could not reproduce. Perhaps you ran `/swim` in a location that is not available.
I will close this issue with a modification to output a more detailed message.

**Closed** 2024-07-24 07:01 UTC
